name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      run: sudo apt-get install -y yasm

    - name: Checkout Payload
      uses: actions/checkout@v3

    - name: Build hen
      run: |
        cd hen
        make         

    - name: Build ftpsrv
      run: |
        cd ftpsrv
        make

    - name: Build _old_jump_table_exploit
      run: |
        cd _old_jump_table_exploit
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: payloads
        path: |
          ./**/*.bin
          ./**/*.elf