name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      run: sudo apt-get install -y yasm

    - name: Build ps5-kstuff
      run: |
        cd ps5-kstuff
        make         

    - name: Build ps5-self-dumper
      run: |
        cd ps5-self-dumper
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: payloads
        path: |
          ./**/*.bin
          ./**/*.elf
