name: Build and Release

on:
  push:
  branches:
      - bd-jb
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        fetch-depth: 0
        ref: bd-jb
        submodules: 'recursive'
        
    - name: Count commits
      id: count-commits
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Commit count: $COMMIT_COUNT"
        echo "::set-output name=commit_count::$COMMIT_COUNT"
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yasm
        
    - name: Run make
      run: |
        cd ps5-kstuff
        make
        cd gdb_stub
        make
        cd pldldr
        make  

      - name: Create release zip
        run: zip -r release.zip .
        if: success()

      - name: Upload release.zip to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       